[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "nova2026"
version = "0.1.0"
description = "NOVA2026 Buildathon Project"
authors = [
    { name = "Yanye Lin", email = "kineticjetice245@gmail.com" },
    { name = "Floryan Lacroix", email = "floryan.lacroix@gmail.com"},
    { name = "Selina Zhou", email = "selinazh06@gmail.com"},
    { name = "Yutong Lu", email = "luyutong505531@gmail.com"}
]
readme = "README.md"
# license = { text = "MIT" }
requires-python = ">=3.12"
dependencies = [
    "mne>=1.12",
    "numpy>=2.5",
    "scipy>=1.18",
    "matplotlib>=3.11",
    "pandas>=3.0.5",
    "torch>=2.0",
    "torchvision>=0.17",
    "scikit-learn>=1.9.0",
    "mne-lsl>=1.14.0",
]

 #
 # [tool.uv.sources]
 # torch = { index = "pytorch-cu132" }
 # torchvision = { index = "pytorch-cu132" }
 #
 # [[tool.uv.index]]
 # name = "pytorch-cu132"
 # url = "https://download.pytorch.org/whl/cu132"
 # explicit = true
 #
 #
[project.optional-dependencies]
dev = []

[tool.setuptools]
package-dir = { "" = "src" } # src as root

[tool.setuptools.packages.find]
where = ["src"] # packages are under src
